language: node_js
node_js:
  - "8"
env:
    - NODE_ENV='test'
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - "node_modules/mocha/bin/mocha --require @babel/register --exit"
