language: node_js
node_js:
  - "8"
env:
    - NODE_ENV='test' SECRET='secret' DATABASE_URL='mongodb://localhost/foundernest'
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - "node_modules/mocha/bin/mocha --require @babel/register --exit"
